name: mllab-venv
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - numpy
  - pandas
  - pip
  - seaborn
  - matplotlib
  - tqdm
  - scikit-learn

